import type { Resource, User } from './types'

export const mockCurrentUser: User = {
  id: 'user-admin',
  name: '管理员',
  department: '计算机科学与技术学院',
  role: 'admin',
}

export const mockUsers: User[] = [
  mockCurrentUser,
  { id: 'user-1', name: '张教授', department: '计算机科学与技术学院', role: 'teacher' },
  { id: 'user-2', name: '李老师', department: '电子信息工程学院', role: 'teacher' },
  { id: 'user-3', name: '王老师', department: '机械工程学院', role: 'teacher' },
  { id: 'user-4', name: '赵老师', department: '土木工程学院', role: 'teacher' },
  { id: 'user-5', name: '孙教授', department: '经济管理学院', role: 'teacher' },
  { id: 'user-6', name: '周老师', department: '外国语学院', role: 'teacher' },
  { id: 'user-7', name: '吴老师', department: '理学院', role: 'teacher' },
  { id: 'user-8', name: '郑老师', department: '艺术学院', role: 'teacher' },
]

export const mockResources: Resource[] = [
  {
    id: 'res-1',
    title: '高等数学（上）精品课程视频',
    type: 'video',
    description: '本课程为高等数学（上）完整教学视频，共48课时，涵盖函数与极限、导数与微分、微分中值定理等内容。视频画质清晰，教师讲解详细，适合大一新生学习使用。',
    content: '/files/math-video.mp4',
    tags: ['高等数学', '微积分', '精品课程'],
    status: 'approved',
    usageCount: 2834,
    favoriteCount: 156,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '理学院',
    major: '数学与应用数学',
    fileUrl: '/files/math-video.mp4',
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'res-2',
    title: '数据结构与算法教学大纲',
    type: 'document',
    description: '计算机科学与技术专业核心课程《数据结构与算法》的完整教学大纲，包含课程目标、教学内容、考核方式等。',
    content: '/files/ds-syllabus.pdf',
    tags: ['数据结构', '算法', '教学大纲'],
    status: 'approved',
    usageCount: 1520,
    favoriteCount: 89,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '计算机科学与技术',
    fileUrl: '/files/ds-syllabus.pdf',
    createdAt: new Date('2025-08-20'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'res-3',
    title: '2025年度教学成果统计表',
    type: 'spreadsheet',
    description: '学院各专业2025年度教学成果统计，包含科研成果、教学获奖、学生竞赛等数据汇总。',
    content: '/files/teaching-stats.xlsx',
    tags: ['教学成果', '统计', '年度报告'],
    status: 'approved',
    usageCount: 687,
    favoriteCount: 34,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '软件工程',
    fileUrl: '/files/teaching-stats.xlsx',
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'res-4',
    title: '实验室设备实拍图集',
    type: 'image',
    description: '计算机实验室最新设备实拍图片，包括服务器、交换机、工控机等设备的高清照片。',
    content: '/files/lab-photos.zip',
    tags: ['实验室', '设备', '图片'],
    status: 'approved',
    usageCount: 1203,
    favoriteCount: 67,
    uploaderId: 'user-3',
    uploaderName: '王老师',
    uploaderDepartment: '机械工程学院',
    department: '计算机科学与技术学院',
    major: '人工智能',
    fileUrl: '/files/lab-photos.zip',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'res-5',
    title: '中国大学MOOC平台链接',
    type: 'link',
    description: '中国大学MOOC平台入口，包含大量优质在线课程资源，支持自主学习与认证。',
    content: 'https://www.icourse163.org',
    tags: ['MOOC', '在线课程', '自主学习'],
    status: 'approved',
    usageCount: 4521,
    favoriteCount: 213,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '经济管理学院',
    major: '工商管理',
    linkUrl: 'https://www.icourse163.org',
    linkSource: '中国大学MOOC',
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'res-6',
    title: '英语听力训练音频集',
    type: 'audio',
    description: '大学英语四六级听力训练音频合集，包含真题听力、模拟训练等音频材料。',
    content: '/files/english-listening.zip',
    tags: ['英语', '听力', '四六级'],
    status: 'approved',
    usageCount: 3156,
    favoriteCount: 178,
    uploaderId: 'user-6',
    uploaderName: '周老师',
    uploaderDepartment: '外国语学院',
    department: '外国语学院',
    major: '英语',
    fileUrl: '/files/english-listening.zip',
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'res-7',
    title: '多功能学术报告厅',
    type: 'venue',
    description: '可容纳200人的多功能学术报告厅，配备投影仪、音响系统、视频会议设备，适合举办学术讲座和大型会议。',
    content: '学术报告厅A101',
    tags: ['报告厅', '学术讲座', '会议'],
    status: 'approved',
    usageCount: 892,
    favoriteCount: 45,
    uploaderId: 'user-4',
    uploaderName: '赵老师',
    uploaderDepartment: '土木工程学院',
    department: '土木工程学院',
    major: '土木工程',
    venueCapacity: 200,
    venueLocation: '主教学楼A101',
    venueFacilities: '投影仪、音响系统、视频会议设备、空调',
    createdAt: new Date('2025-08-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'res-8',
    title: '高性能计算服务器集群',
    type: 'equipment',
    description: '由16台节点组成的HPC集群，总核心数256核，内存1TB，适用于大规模科学计算和AI训练。',
    content: 'HPC-Cluster-001',
    tags: ['服务器', 'HPC', 'AI训练'],
    status: 'approved',
    usageCount: 567,
    favoriteCount: 32,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '人工智能',
    equipmentModel: 'Dell PowerEdge R750',
    equipmentSpec: '256核 / 1TB内存 / 50TB存储',
    equipmentLocation: '计算机中心3楼机房',
    equipmentManager: '张教授',
    createdAt: new Date('2025-07-15'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'res-9',
    title: 'MATLAB R2024a 科学计算软件',
    type: 'software',
    description: 'MATLAB R2024a学术版，包含Simulink、信号处理、图像处理等工具箱，支持全校师生使用。',
    content: 'MATLAB R2024a Academic',
    tags: ['MATLAB', '科学计算', '仿真'],
    status: 'approved',
    usageCount: 2845,
    favoriteCount: 123,
    uploaderId: 'user-7',
    uploaderName: '吴老师',
    uploaderDepartment: '理学院',
    department: '理学院',
    major: '物理学',
    softwareVersion: 'R2024a',
    softwareEnv: 'Windows 10/11, macOS, Linux',
    softwareLicense: 'Academic Campus License',
    softwareDownloadUrl: 'https://matlab.example.edu/download',
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'res-10',
    title: '电路原理虚拟仿真实验',
    type: 'simulation',
    description: '基于SPICE引擎的电路原理虚拟仿真实验平台，支持电阻、电容、电感等元件的电路搭建与仿真分析。',
    content: '/sim/circuit-lab',
    tags: ['电路', '虚拟仿真', '实验'],
    status: 'approved',
    usageCount: 1678,
    favoriteCount: 94,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '电子信息工程学院',
    major: '电子信息工程',
    simulationPlatform: 'Web-based SPICE Simulator',
    simulationDomain: '电子电路',
    simulationInstructions: '登录后选择实验项目，拖拽元件搭建电路，点击运行查看仿真结果。',
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'res-11',
    title: '机械设计基础3D模型库',
    type: 'other',
    description: '包含齿轮、轴承、连杆机构等常用机械零件的3D模型文件，支持STL、STEP等格式。',
    content: '/files/mechanical-models.zip',
    tags: ['机械设计', '3D模型', '零件库'],
    status: 'approved',
    usageCount: 1034,
    favoriteCount: 56,
    uploaderId: 'user-3',
    uploaderName: '王老师',
    uploaderDepartment: '机械工程学院',
    department: '机械工程学院',
    major: '机械设计制造及其自动化',
    fileUrl: '/files/mechanical-models.zip',
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'res-12',
    title: 'Python编程入门教学视频',
    type: 'video',
    description: '面向零基础学生的Python编程入门系列课程，从变量、数据类型到函数、面向对象编程，循序渐进。',
    content: '/files/python-intro.mp4',
    tags: ['Python', '编程', '入门'],
    status: 'approved',
    usageCount: 3200,
    favoriteCount: 201,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '软件工程',
    fileUrl: '/files/python-intro.mp4',
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'res-13',
    title: '毕业设计论文模板',
    type: 'document',
    description: '本科毕业设计（论文）标准模板，包含封面、摘要、目录、正文、参考文献等格式要求。',
    content: '/files/thesis-template.docx',
    tags: ['毕业论文', '模板', '格式'],
    status: 'approved',
    usageCount: 890,
    favoriteCount: 45,
    uploaderId: 'user-4',
    uploaderName: '赵老师',
    uploaderDepartment: '土木工程学院',
    department: '教务处',
    fileUrl: '/files/thesis-template.docx',
    createdAt: new Date('2025-10-10'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'res-14',
    title: '艺术设计色彩理论讲座视频',
    type: 'video',
    description: '艺术学院举办的色彩理论专题讲座录像，涵盖色彩心理学、配色原理及设计应用。',
    content: '/files/color-theory.mp4',
    tags: ['色彩理论', '艺术设计', '讲座'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-8',
    uploaderName: '郑老师',
    uploaderDepartment: '艺术学院',
    department: '艺术学院',
    fileUrl: '/files/color-theory.mp4',
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: 'res-15',
    title: '经管类案例分析合集',
    type: 'document',
    description: '包含市场营销、人力资源管理、财务管理等方向的经典案例分析，适用于课堂讨论。',
    content: '/files/business-cases.pdf',
    tags: ['案例分析', '经管', '教学案例'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '经济管理学院',
    fileUrl: '/files/business-cases.pdf',
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'res-16',
    title: '过时的教材扫描版（已驳回）',
    type: 'document',
    description: '某旧版教材扫描件，内容已过时。',
    content: '/files/old-book.pdf',
    tags: ['教材', '扫描'],
    status: 'rejected',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    rejectReason: '内容已过时，请更新为最新版本教材。',
    fileUrl: '/files/old-book.pdf',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-08'),
  },
  {
    id: 'res-17',
    title: '物理实验虚拟仿真平台',
    type: 'simulation',
    description: '涵盖力学、热学、光学、电磁学等大学物理实验的虚拟仿真平台，支持在线操作和数据记录。',
    content: '/sim/physics-lab',
    tags: ['物理实验', '虚拟仿真', '在线实验'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-7',
    uploaderName: '吴老师',
    uploaderDepartment: '理学院',
    department: '理学院',
    simulationPlatform: 'WebGL Physics Engine',
    simulationDomain: '大学物理',
    simulationInstructions: '选择实验项目后按步骤操作，记录数据并生成实验报告。',
    createdAt: new Date('2026-03-12'),
    updatedAt: new Date('2026-03-12'),
  },
  {
    id: 'res-18',
    title: '学院小礼堂',
    type: 'venue',
    description: '可容纳100人的多功能小礼堂，适合举办小型学术交流会和文艺活动。',
    content: '学院小礼堂B201',
    tags: ['小礼堂', '学术交流', '文艺活动'],
    status: 'approved',
    usageCount: 556,
    favoriteCount: 28,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '网络工程',
    venueCapacity: 100,
    venueLocation: '学院楼B201',
    venueFacilities: '投影仪、音响、舞台灯光、钢琴',
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'res-19',
    title: '示波器 Tektronix MDO3024',
    type: 'equipment',
    description: 'Tektronix MDO3024混合域示波器，200MHz带宽，4个模拟通道，内置频谱分析仪。',
    content: 'Tektronix-MDO3024-001',
    tags: ['示波器', '测量仪器', '电子实验'],
    status: 'approved',
    usageCount: 234,
    favoriteCount: 12,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '电子信息工程学院',
    major: '通信工程',
    equipmentModel: 'Tektronix MDO3024',
    equipmentSpec: '200MHz / 4通道 / 2.5GS/s',
    equipmentLocation: '电子实验中心201室',
    equipmentManager: '李老师',
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'res-20',
    title: 'VMware Workstation Pro 17',
    type: 'software',
    description: 'VMware虚拟机软件专业版，支持多操作系统虚拟机运行，适用于实验教学环境搭建。',
    content: 'VMware Workstation Pro 17',
    tags: ['虚拟机', '操作系统', '实验环境'],
    status: 'approved',
    usageCount: 1567,
    favoriteCount: 78,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '网络工程',
    softwareVersion: '17.5',
    softwareEnv: 'Windows 10/11, Linux',
    softwareLicense: 'Academic Site License',
    softwareDownloadUrl: 'https://vmware.example.edu/download',
    createdAt: new Date('2025-08-15'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'res-21',
    title: '日语入门五十音图音频',
    type: 'audio',
    description: '日语五十音图标准发音音频，包含平假名和片假名的正确读音示范。',
    content: '/files/japanese-50on.mp3',
    tags: ['日语', '五十音', '发音'],
    status: 'approved',
    usageCount: 789,
    favoriteCount: 43,
    uploaderId: 'user-6',
    uploaderName: '周老师',
    uploaderDepartment: '外国语学院',
    department: '外国语学院',
    major: '日语',
    fileUrl: '/files/japanese-50on.mp3',
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'res-22',
    title: '校园建筑CAD图纸集',
    type: 'image',
    description: '校园主要建筑CAD设计图纸合集，包含教学楼、图书馆、食堂等建筑的平面图、立面图。',
    content: '/files/campus-cad.zip',
    tags: ['CAD', '建筑图纸', '校园'],
    status: 'approved',
    usageCount: 345,
    favoriteCount: 15,
    uploaderId: 'user-4',
    uploaderName: '赵老师',
    uploaderDepartment: '土木工程学院',
    department: '土木工程学院',
    major: '建筑学',
    fileUrl: '/files/campus-cad.zip',
    createdAt: new Date('2025-12-20'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'res-23',
    title: '知网学术资源链接',
    type: 'link',
    description: '中国知网CNKI学术资源总库入口，提供学术期刊、博硕士论文、会议论文等文献检索服务。',
    content: 'https://www.cnki.net',
    tags: ['知网', '文献检索', '学术资源'],
    status: 'approved',
    usageCount: 6023,
    favoriteCount: 356,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '图书馆',
    linkUrl: 'https://www.cnki.net',
    linkSource: '中国知网',
    createdAt: new Date('2025-05-15'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'res-24',
    title: '学生成绩统计表模板',
    type: 'spreadsheet',
    description: '标准化学生成绩统计Excel模板，支持平时成绩、期中考试、期末考试等多项成绩汇总与自动统计。',
    content: '/files/score-template.xlsx',
    tags: ['成绩统计', 'Excel', '模板'],
    status: 'approved',
    usageCount: 2134,
    favoriteCount: 98,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '计算机科学与技术',
    fileUrl: '/files/score-template.xlsx',
    createdAt: new Date('2025-09-25'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'res-kp-1',
    title: '导数与微分',
    type: 'knowledge-point',
    description: '导数的定义、几何意义及基本求导法则，微分的概念及其在近似计算中的应用，是高等数学的核心基础内容。',
    content: 'MATH-101-001',
    tags: ['高等数学', '微积分', '导数'],
    status: 'approved',
    usageCount: 1823,
    favoriteCount: 87,
    uploaderId: 'user-7',
    uploaderName: '吴老师',
    uploaderDepartment: '理学院',
    department: '理学院',
    major: '数学与应用数学',
    knowledgeCode: 'MATH-101-001',
    knowledgeCourses: '高等数学（上）,微积分进阶',
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'res-kp-2',
    title: '线性表与链表',
    type: 'knowledge-point',
    description: '顺序表与链式存储结构的定义、操作实现及时间复杂度分析，是数据结构课程的核心知识点。',
    content: 'CS-201-003',
    tags: ['数据结构', '线性表', '链表'],
    status: 'approved',
    usageCount: 1456,
    favoriteCount: 68,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '计算机科学与技术',
    knowledgeCode: 'CS-201-003',
    knowledgeCourses: '数据结构与算法,算法分析与设计',
    createdAt: new Date('2025-10-05'),
    updatedAt: new Date('2026-01-18'),
  },
  {
    id: 'res-kp-3',
    title: '欧姆定律与基尔霍夫定律',
    type: 'knowledge-point',
    description: '欧姆定律的三种形式及适用范围，基尔霍夫电流定律与电压定律的电路分析方法。',
    content: 'EE-301-007',
    tags: ['电路原理', '欧姆定律', '基尔霍夫定律'],
    status: 'approved',
    usageCount: 987,
    favoriteCount: 45,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '电子信息工程学院',
    major: '电子信息工程',
    knowledgeCode: 'EE-301-007',
    knowledgeCourses: '电路原理,模拟电子技术',
    createdAt: new Date('2025-09-22'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'res-kp-4',
    title: '正弦交流电路分析',
    type: 'knowledge-point',
    description: '正弦量的相量表示法、RLC串联/并联电路分析、谐振电路特性及功率因数补偿方法。',
    content: 'EE-301-012',
    tags: ['交流电路', '相量法', '谐振'],
    status: 'approved',
    usageCount: 756,
    favoriteCount: 32,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '电子信息工程学院',
    major: '通信工程',
    knowledgeCode: 'EE-301-012',
    knowledgeCourses: '电路原理,电工学',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'res-kp-5',
    title: '面向对象程序设计',
    type: 'knowledge-point',
    description: '类与对象、封装性、继承与多态等面向对象核心概念，以及UML类图的基本表示方法。',
    content: 'CS-102-005',
    tags: ['面向对象', 'Java', '封装继承多态'],
    status: 'approved',
    usageCount: 2100,
    favoriteCount: 112,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '软件工程',
    knowledgeCode: 'CS-102-005',
    knowledgeCourses: '程序设计基础,Java面向对象编程,软件工程',
    createdAt: new Date('2025-08-25'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'res-kp-6',
    title: '英语时态综合运用',
    type: 'knowledge-point',
    description: '一般现在时、一般过去时、现在完成时等八大时态的定义、构成及在写作和翻译中的应用场景。',
    content: 'ENG-101-002',
    tags: ['英语语法', '时态', '四六级'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-6',
    uploaderName: '周老师',
    uploaderDepartment: '外国语学院',
    department: '外国语学院',
    major: '英语',
    knowledgeCode: 'ENG-101-002',
    knowledgeCourses: '大学英语（一）,英语语法进阶',
    createdAt: new Date('2026-03-18'),
    updatedAt: new Date('2026-03-18'),
  },
  {
    id: 'res-ap-1',
    title: '编程实现能力',
    type: 'ability-point',
    description: '能够运用至少一门编程语言独立完成中等规模的程序设计，包括需求分析、编码实现与基本调试。',
    content: '编程实现能力',
    tags: ['编程', '软件开发', '编码'],
    status: 'approved',
    usageCount: 2356,
    favoriteCount: 145,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    major: '计算机科学与技术',
    abilityDomain: '软件开发能力域',
    abilityCode: 'SD-001',
    abilityAttribute: 'skill',
    abilityMastery: 'proficient',
    abilityStandard: '能够独立完成2000行以上的程序设计，通过单元测试覆盖率达到80%以上，代码符合企业编码规范。',
    createdAt: new Date('2025-08-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'res-ap-2',
    title: '数据分析与建模能力',
    type: 'ability-point',
    description: '掌握数据采集、清洗、分析及可视化方法，能够建立数学模型解决实际业务问题。',
    content: '数据分析与建模能力',
    tags: ['数据分析', '建模', '统计'],
    status: 'approved',
    usageCount: 1876,
    favoriteCount: 98,
    uploaderId: 'user-7',
    uploaderName: '吴老师',
    uploaderDepartment: '理学院',
    department: '理学院',
    major: '应用化学',
    abilityDomain: '数据科学能力域',
    abilityCode: 'DS-003',
    abilityAttribute: 'knowledge',
    abilityMastery: 'master',
    abilityStandard: '能够运用Python/R完成完整的数据分析项目，产出数据分析报告并可视化展示关键结论。',
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'res-ap-3',
    title: '团队协作与沟通能力',
    type: 'ability-point',
    description: '在团队项目中主动承担责任，有效沟通表达观点，协调分工推动项目进展。',
    content: '团队协作与沟通能力',
    tags: ['团队协作', '沟通', '项目管理'],
    status: 'approved',
    usageCount: 3210,
    favoriteCount: 203,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '经济管理学院',
    major: '工商管理',
    abilityDomain: '通用素养能力域',
    abilityCode: 'GEN-005',
    abilityAttribute: 'literacy',
    abilityMastery: 'proficient',
    abilityStandard: '能够在跨专业团队中担任组长角色，组织有效的团队会议，产出符合预期的项目成果。',
    createdAt: new Date('2025-07-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'res-ap-4',
    title: '电路设计与调试能力',
    type: 'ability-point',
    description: '能够设计模拟/数字电路并完成调试，熟练使用示波器、信号发生器等常用电子测量仪器。',
    content: '电路设计与调试能力',
    tags: ['电路设计', '调试', '测量仪器'],
    status: 'approved',
    usageCount: 1345,
    favoriteCount: 67,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '电子信息工程学院',
    major: '微电子科学与工程',
    abilityDomain: '电子工程能力域',
    abilityCode: 'EE-007',
    abilityAttribute: 'skill',
    abilityMastery: 'master',
    abilityStandard: '能够独立完成包含10个以上元件的电路设计与调试，熟练使用示波器进行信号分析。',
    createdAt: new Date('2025-10-12'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'res-ap-5',
    title: '学术文献检索与综述能力',
    type: 'ability-point',
    description: '掌握中英文学术数据库的使用方法，能够高效检索文献并进行系统性的文献综述。',
    content: '学术文献检索与综述能力',
    tags: ['文献检索', '综述', '学术研究'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-4',
    uploaderName: '赵老师',
    uploaderDepartment: '土木工程学院',
    department: '土木工程学院',
    major: '土木工程',
    abilityDomain: '研究素养能力域',
    abilityCode: 'RES-002',
    abilityAttribute: 'literacy',
    abilityMastery: 'understand',
    abilityStandard: '能够使用CNKI、Web of Science等数据库检索文献，独立完成至少5000字的文献综述报告。',
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'res-ap-6',
    title: '项目管理基础知识',
    type: 'ability-point',
    description: '了解项目管理的九大知识领域和五大过程组，掌握WBS、甘特图等基本项目管理工具。',
    content: '项目管理基础知识',
    tags: ['项目管理', 'WBS', '甘特图'],
    status: 'approved',
    usageCount: 1567,
    favoriteCount: 76,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '经济管理学院',
    major: '工商管理',
    abilityDomain: '管理能力域',
    abilityCode: 'MGT-001',
    abilityAttribute: 'knowledge',
    abilityMastery: 'comprehend',
    abilityStandard: '能够绘制WBS结构图和甘特图，理解项目管理全流程的基本概念和关键节点。',
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2026-02-28'),
  },
]

export const mockFavoriteIds: Set<string> = new Set([
  'res-1', 'res-5', 'res-9', 'res-10', 'res-12',
])

export function getResourceTypeStats(resources: Resource[]) {
  const approved = resources.filter((r) => r.status === 'approved')
  return {
    total: approved.length,
    video: approved.filter((r) => r.type === 'video').length,
    document: approved.filter((r) => r.type === 'document').length,
    spreadsheet: approved.filter((r) => r.type === 'spreadsheet').length,
    image: approved.filter((r) => r.type === 'image').length,
    link: approved.filter((r) => r.type === 'link').length,
    audio: approved.filter((r) => r.type === 'audio').length,
    venue: approved.filter((r) => r.type === 'venue').length,
    equipment: approved.filter((r) => r.type === 'equipment').length,
    software: approved.filter((r) => r.type === 'software').length,
    simulation: approved.filter((r) => r.type === 'simulation').length,
    other: approved.filter((r) => r.type === 'other').length,
    'knowledge-point': approved.filter((r) => r.type === 'knowledge-point').length,
    'ability-point': approved.filter((r) => r.type === 'ability-point').length,
  }
}
