import type { Resource, User } from './types'

export const mockCurrentUser: User = {
  id: 'user-admin',
  name: '管理员',
  department: '计算机科学与技术学院',
  role: 'admin',
}

export const mockUsers: User[] = [
  mockCurrentUser,
  { id: 'user-1', name: '张教授', department: '计算机科学与技术学院', role: 'teacher' },
  { id: 'user-2', name: '李老师', department: '电子信息工程学院', role: 'teacher' },
  { id: 'user-3', name: '王老师', department: '机械工程学院', role: 'teacher' },
  { id: 'user-4', name: '赵老师', department: '土木工程学院', role: 'teacher' },
  { id: 'user-5', name: '孙教授', department: '经济管理学院', role: 'teacher' },
  { id: 'user-6', name: '周老师', department: '外国语学院', role: 'teacher' },
  { id: 'user-7', name: '吴老师', department: '理学院', role: 'teacher' },
  { id: 'user-8', name: '郑老师', department: '艺术学院', role: 'teacher' },
]

export const mockResources: Resource[] = [
  {
    id: 'res-1',
    title: '高等数学（上）精品课程视频',
    type: 'video',
    description: '本课程为高等数学（上）完整教学视频，共48课时，涵盖函数与极限、导数与微分、微分中值定理等内容。视频画质清晰，教师讲解详细，适合大一新生学习使用。',
    content: '/files/math-video.mp4',
    tags: ['高等数学', '微积分', '精品课程'],
    status: 'approved',
    usageCount: 2834,
    favoriteCount: 156,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '理学院',
    fileUrl: '/files/math-video.mp4',
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'res-2',
    title: '数据结构与算法教学大纲',
    type: 'document',
    description: '计算机科学与技术专业核心课程《数据结构与算法》的完整教学大纲，包含课程目标、教学内容、考核方式等。',
    content: '/files/ds-syllabus.pdf',
    tags: ['数据结构', '算法', '教学大纲'],
    status: 'approved',
    usageCount: 1520,
    favoriteCount: 89,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    fileUrl: '/files/ds-syllabus.pdf',
    createdAt: new Date('2025-08-20'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'res-3',
    title: '2025年度教学成果统计表',
    type: 'spreadsheet',
    description: '学院各专业2025年度教学成果统计，包含科研成果、教学获奖、学生竞赛等数据汇总。',
    content: '/files/teaching-stats.xlsx',
    tags: ['教学成果', '统计', '年度报告'],
    status: 'approved',
    usageCount: 687,
    favoriteCount: 34,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    fileUrl: '/files/teaching-stats.xlsx',
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'res-4',
    title: '实验室设备实拍图集',
    type: 'image',
    description: '计算机实验室最新设备实拍图片，包括服务器、交换机、工控机等设备的高清照片。',
    content: '/files/lab-photos.zip',
    tags: ['实验室', '设备', '图片'],
    status: 'approved',
    usageCount: 1203,
    favoriteCount: 67,
    uploaderId: 'user-3',
    uploaderName: '王老师',
    uploaderDepartment: '机械工程学院',
    department: '计算机科学与技术学院',
    fileUrl: '/files/lab-photos.zip',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'res-5',
    title: '中国大学MOOC平台链接',
    type: 'link',
    description: '中国大学MOOC平台入口，包含大量优质在线课程资源，支持自主学习与认证。',
    content: 'https://www.icourse163.org',
    tags: ['MOOC', '在线课程', '自主学习'],
    status: 'approved',
    usageCount: 4521,
    favoriteCount: 213,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '经济管理学院',
    linkUrl: 'https://www.icourse163.org',
    linkSource: '中国大学MOOC',
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'res-6',
    title: '英语听力训练音频集',
    type: 'audio',
    description: '大学英语四六级听力训练音频合集，包含真题听力、模拟训练等音频材料。',
    content: '/files/english-listening.zip',
    tags: ['英语', '听力', '四六级'],
    status: 'approved',
    usageCount: 3156,
    favoriteCount: 178,
    uploaderId: 'user-6',
    uploaderName: '周老师',
    uploaderDepartment: '外国语学院',
    department: '外国语学院',
    fileUrl: '/files/english-listening.zip',
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'res-7',
    title: '多功能学术报告厅',
    type: 'venue',
    description: '可容纳200人的多功能学术报告厅，配备投影仪、音响系统、视频会议设备，适合举办学术讲座和大型会议。',
    content: '学术报告厅A101',
    tags: ['报告厅', '学术讲座', '会议'],
    status: 'approved',
    usageCount: 892,
    favoriteCount: 45,
    uploaderId: 'user-4',
    uploaderName: '赵老师',
    uploaderDepartment: '土木工程学院',
    department: '土木工程学院',
    venueCapacity: 200,
    venueLocation: '主教学楼A101',
    venueFacilities: '投影仪、音响系统、视频会议设备、空调',
    createdAt: new Date('2025-08-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'res-8',
    title: '高性能计算服务器集群',
    type: 'equipment',
    description: '由16台节点组成的HPC集群，总核心数256核，内存1TB，适用于大规模科学计算和AI训练。',
    content: 'HPC-Cluster-001',
    tags: ['服务器', 'HPC', 'AI训练'],
    status: 'approved',
    usageCount: 567,
    favoriteCount: 32,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    equipmentModel: 'Dell PowerEdge R750',
    equipmentSpec: '256核 / 1TB内存 / 50TB存储',
    equipmentLocation: '计算机中心3楼机房',
    equipmentManager: '张教授',
    createdAt: new Date('2025-07-15'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'res-9',
    title: 'MATLAB R2024a 科学计算软件',
    type: 'software',
    description: 'MATLAB R2024a学术版，包含Simulink、信号处理、图像处理等工具箱，支持全校师生使用。',
    content: 'MATLAB R2024a Academic',
    tags: ['MATLAB', '科学计算', '仿真'],
    status: 'approved',
    usageCount: 2845,
    favoriteCount: 123,
    uploaderId: 'user-7',
    uploaderName: '吴老师',
    uploaderDepartment: '理学院',
    department: '理学院',
    softwareVersion: 'R2024a',
    softwareEnv: 'Windows 10/11, macOS, Linux',
    softwareLicense: 'Academic Campus License',
    softwareDownloadUrl: 'https://matlab.example.edu/download',
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'res-10',
    title: '电路原理虚拟仿真实验',
    type: 'simulation',
    description: '基于SPICE引擎的电路原理虚拟仿真实验平台，支持电阻、电容、电感等元件的电路搭建与仿真分析。',
    content: '/sim/circuit-lab',
    tags: ['电路', '虚拟仿真', '实验'],
    status: 'approved',
    usageCount: 1678,
    favoriteCount: 94,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '电子信息工程学院',
    simulationPlatform: 'Web-based SPICE Simulator',
    simulationDomain: '电子电路',
    simulationInstructions: '登录后选择实验项目，拖拽元件搭建电路，点击运行查看仿真结果。',
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'res-11',
    title: '机械设计基础3D模型库',
    type: 'other',
    description: '包含齿轮、轴承、连杆机构等常用机械零件的3D模型文件，支持STL、STEP等格式。',
    content: '/files/mechanical-models.zip',
    tags: ['机械设计', '3D模型', '零件库'],
    status: 'approved',
    usageCount: 1034,
    favoriteCount: 56,
    uploaderId: 'user-3',
    uploaderName: '王老师',
    uploaderDepartment: '机械工程学院',
    department: '机械工程学院',
    fileUrl: '/files/mechanical-models.zip',
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'res-12',
    title: 'Python编程入门教学视频',
    type: 'video',
    description: '面向零基础学生的Python编程入门系列课程，从变量、数据类型到函数、面向对象编程，循序渐进。',
    content: '/files/python-intro.mp4',
    tags: ['Python', '编程', '入门'],
    status: 'approved',
    usageCount: 3200,
    favoriteCount: 201,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    fileUrl: '/files/python-intro.mp4',
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'res-13',
    title: '毕业设计论文模板',
    type: 'document',
    description: '本科毕业设计（论文）标准模板，包含封面、摘要、目录、正文、参考文献等格式要求。',
    content: '/files/thesis-template.docx',
    tags: ['毕业论文', '模板', '格式'],
    status: 'approved',
    usageCount: 890,
    favoriteCount: 45,
    uploaderId: 'user-4',
    uploaderName: '赵老师',
    uploaderDepartment: '土木工程学院',
    department: '教务处',
    fileUrl: '/files/thesis-template.docx',
    createdAt: new Date('2025-10-10'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'res-14',
    title: '艺术设计色彩理论讲座视频',
    type: 'video',
    description: '艺术学院举办的色彩理论专题讲座录像，涵盖色彩心理学、配色原理及设计应用。',
    content: '/files/color-theory.mp4',
    tags: ['色彩理论', '艺术设计', '讲座'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-8',
    uploaderName: '郑老师',
    uploaderDepartment: '艺术学院',
    department: '艺术学院',
    fileUrl: '/files/color-theory.mp4',
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: 'res-15',
    title: '经管类案例分析合集',
    type: 'document',
    description: '包含市场营销、人力资源管理、财务管理等方向的经典案例分析，适用于课堂讨论。',
    content: '/files/business-cases.pdf',
    tags: ['案例分析', '经管', '教学案例'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '经济管理学院',
    fileUrl: '/files/business-cases.pdf',
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'res-16',
    title: '过时的教材扫描版（已驳回）',
    type: 'document',
    description: '某旧版教材扫描件，内容已过时。',
    content: '/files/old-book.pdf',
    tags: ['教材', '扫描'],
    status: 'rejected',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-1',
    uploaderName: '张教授',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    rejectReason: '内容已过时，请更新为最新版本教材。',
    fileUrl: '/files/old-book.pdf',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-08'),
  },
  {
    id: 'res-17',
    title: '物理实验虚拟仿真平台',
    type: 'simulation',
    description: '涵盖力学、热学、光学、电磁学等大学物理实验的虚拟仿真平台，支持在线操作和数据记录。',
    content: '/sim/physics-lab',
    tags: ['物理实验', '虚拟仿真', '在线实验'],
    status: 'pending',
    usageCount: 0,
    favoriteCount: 0,
    uploaderId: 'user-7',
    uploaderName: '吴老师',
    uploaderDepartment: '理学院',
    department: '理学院',
    simulationPlatform: 'WebGL Physics Engine',
    simulationDomain: '大学物理',
    simulationInstructions: '选择实验项目后按步骤操作，记录数据并生成实验报告。',
    createdAt: new Date('2026-03-12'),
    updatedAt: new Date('2026-03-12'),
  },
  {
    id: 'res-18',
    title: '学院小礼堂',
    type: 'venue',
    description: '可容纳100人的多功能小礼堂，适合举办小型学术交流会和文艺活动。',
    content: '学院小礼堂B201',
    tags: ['小礼堂', '学术交流', '文艺活动'],
    status: 'approved',
    usageCount: 556,
    favoriteCount: 28,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    venueCapacity: 100,
    venueLocation: '学院楼B201',
    venueFacilities: '投影仪、音响、舞台灯光、钢琴',
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'res-19',
    title: '示波器 Tektronix MDO3024',
    type: 'equipment',
    description: 'Tektronix MDO3024混合域示波器，200MHz带宽，4个模拟通道，内置频谱分析仪。',
    content: 'Tektronix-MDO3024-001',
    tags: ['示波器', '测量仪器', '电子实验'],
    status: 'approved',
    usageCount: 234,
    favoriteCount: 12,
    uploaderId: 'user-2',
    uploaderName: '李老师',
    uploaderDepartment: '电子信息工程学院',
    department: '电子信息工程学院',
    equipmentModel: 'Tektronix MDO3024',
    equipmentSpec: '200MHz / 4通道 / 2.5GS/s',
    equipmentLocation: '电子实验中心201室',
    equipmentManager: '李老师',
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'res-20',
    title: 'VMware Workstation Pro 17',
    type: 'software',
    description: 'VMware虚拟机软件专业版，支持多操作系统虚拟机运行，适用于实验教学环境搭建。',
    content: 'VMware Workstation Pro 17',
    tags: ['虚拟机', '操作系统', '实验环境'],
    status: 'approved',
    usageCount: 1567,
    favoriteCount: 78,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    softwareVersion: '17.5',
    softwareEnv: 'Windows 10/11, Linux',
    softwareLicense: 'Academic Site License',
    softwareDownloadUrl: 'https://vmware.example.edu/download',
    createdAt: new Date('2025-08-15'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'res-21',
    title: '日语入门五十音图音频',
    type: 'audio',
    description: '日语五十音图标准发音音频，包含平假名和片假名的正确读音示范。',
    content: '/files/japanese-50on.mp3',
    tags: ['日语', '五十音', '发音'],
    status: 'approved',
    usageCount: 789,
    favoriteCount: 43,
    uploaderId: 'user-6',
    uploaderName: '周老师',
    uploaderDepartment: '外国语学院',
    department: '外国语学院',
    fileUrl: '/files/japanese-50on.mp3',
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'res-22',
    title: '校园建筑CAD图纸集',
    type: 'image',
    description: '校园主要建筑CAD设计图纸合集，包含教学楼、图书馆、食堂等建筑的平面图、立面图。',
    content: '/files/campus-cad.zip',
    tags: ['CAD', '建筑图纸', '校园'],
    status: 'approved',
    usageCount: 345,
    favoriteCount: 15,
    uploaderId: 'user-4',
    uploaderName: '赵老师',
    uploaderDepartment: '土木工程学院',
    department: '土木工程学院',
    fileUrl: '/files/campus-cad.zip',
    createdAt: new Date('2025-12-20'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'res-23',
    title: '知网学术资源链接',
    type: 'link',
    description: '中国知网CNKI学术资源总库入口，提供学术期刊、博硕士论文、会议论文等文献检索服务。',
    content: 'https://www.cnki.net',
    tags: ['知网', '文献检索', '学术资源'],
    status: 'approved',
    usageCount: 6023,
    favoriteCount: 356,
    uploaderId: 'user-5',
    uploaderName: '孙教授',
    uploaderDepartment: '经济管理学院',
    department: '图书馆',
    linkUrl: 'https://www.cnki.net',
    linkSource: '中国知网',
    createdAt: new Date('2025-05-15'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'res-24',
    title: '学生成绩统计表模板',
    type: 'spreadsheet',
    description: '标准化学生成绩统计Excel模板，支持平时成绩、期中考试、期末考试等多项成绩汇总与自动统计。',
    content: '/files/score-template.xlsx',
    tags: ['成绩统计', 'Excel', '模板'],
    status: 'approved',
    usageCount: 2134,
    favoriteCount: 98,
    uploaderId: 'user-admin',
    uploaderName: '管理员',
    uploaderDepartment: '计算机科学与技术学院',
    department: '计算机科学与技术学院',
    fileUrl: '/files/score-template.xlsx',
    createdAt: new Date('2025-09-25'),
    updatedAt: new Date('2026-01-10'),
  },
]

export const mockFavoriteIds: Set<string> = new Set([
  'res-1', 'res-5', 'res-9', 'res-10', 'res-12',
])

export function getResourceTypeStats(resources: Resource[]) {
  const approved = resources.filter((r) => r.status === 'approved')
  return {
    total: approved.length,
    video: approved.filter((r) => r.type === 'video').length,
    document: approved.filter((r) => r.type === 'document').length,
    spreadsheet: approved.filter((r) => r.type === 'spreadsheet').length,
    image: approved.filter((r) => r.type === 'image').length,
    link: approved.filter((r) => r.type === 'link').length,
    audio: approved.filter((r) => r.type === 'audio').length,
    venue: approved.filter((r) => r.type === 'venue').length,
    equipment: approved.filter((r) => r.type === 'equipment').length,
    software: approved.filter((r) => r.type === 'software').length,
    simulation: approved.filter((r) => r.type === 'simulation').length,
    other: approved.filter((r) => r.type === 'other').length,
  }
}
