import type { QuestionBank, Question, Exam, ExamQuestion, User, KnowledgePoint, Difficulty, Batch, Department } from './types'

// 模拟用户数据
export const mockUsers: User[] = [
  { id: 'user-1', name: '张三', email: 'zhangsan@example.com', department: '前端开发部', avatar: '' },
  { id: 'user-2', name: '李四', email: 'lisi@example.com', department: '后端开发部', avatar: '' },
  { id: 'user-3', name: '王五', email: 'wangwu@example.com', department: '测试部', avatar: '' },
  { id: 'user-4', name: '赵六', email: 'zhaoliu@example.com', department: '产品部', avatar: '' },
  { id: 'user-5', name: '孙七', email: 'sunqi@example.com', department: '前端开发部', avatar: '' },
  { id: 'user-6', name: '周八', email: 'zhouba@example.com', department: '后端开发部', avatar: '' },
  { id: 'user-7', name: '吴九', email: 'wujiu@example.com', department: '设计部', avatar: '' },
  { id: 'user-8', name: '郑十', email: 'zhengshi@example.com', department: '运维部', avatar: '' },
]

// 模拟批次数据
export const mockBatches: Batch[] = [
  { id: 'batch-1', name: '2024年第一季度', description: '2024年Q1考核批次' },
  { id: 'batch-2', name: '2024年第二季度', description: '2024年Q2考核批次' },
  { id: 'batch-3', name: '2024年春季培训', description: '春季新员工培训' },
  { id: 'batch-4', name: '2024年秋季考核', description: '秋季技术考核' },
  { id: 'batch-5', name: '通用题库', description: '不限批次的通用题库' },
]

// 模拟部门数据
export const mockDepartments: Department[] = [
  { id: 'dept-1', name: '前端开发部' },
  { id: 'dept-2', name: '后端开发部' },
  { id: 'dept-3', name: '测试部' },
  { id: 'dept-4', name: '产品部' },
  { id: 'dept-5', name: '设计部' },
  { id: 'dept-6', name: '运维部' },
  { id: 'dept-7', name: '人力资源部' },
]

// 模拟知识点数据
export const mockKnowledgePoints: KnowledgePoint[] = [
  { id: 'kp-1', name: '变量与数据类型' },
  { id: 'kp-2', name: '函数与作用域' },
  { id: 'kp-3', name: '异步编程' },
  { id: 'kp-4', name: '面向对象' },
  { id: 'kp-5', name: 'DOM操作' },
  { id: 'kp-6', name: 'React Hooks' },
  { id: 'kp-7', name: '状态管理' },
  { id: 'kp-8', name: '性能优化' },
  { id: 'kp-9', name: '类型系统' },
  { id: 'kp-10', name: '泛型编程' },
  { id: 'kp-11', name: 'CSS布局' },
  { id: 'kp-12', name: 'CSS动画' },
  { id: 'kp-13', name: 'Node.js基础' },
  { id: 'kp-14', name: 'Express框架' },
]

// 模拟题库数据
export const mockQuestionBanks: QuestionBank[] = [
  {
    id: 'bank-1',
    name: 'JavaScript 基础知识',
    description: '涵盖 JavaScript 核心概念、语法和常见问题',
    status: 'published',
    questionCount: 8,
    collaboratorIds: ['user-2', 'user-3'],
    collaboratorDeptIds: ['dept-1'],
    batchId: 'batch-1',
    version: 'v1.2.0',
    ownerType: 'mine',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'bank-2',
    name: 'React 框架进阶',
    description: 'React Hooks、状态管理、性能优化等进阶内容',
    status: 'toPublish',
    questionCount: 6,
    collaboratorIds: ['user-1'],
    collaboratorDeptIds: ['dept-1', 'dept-2'],
    batchId: 'batch-2',
    version: 'v1.0.0',
    ownerType: 'collaborate',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'bank-3',
    name: 'TypeScript 类型系统',
    description: 'TypeScript 高级类型、泛型、类型推断',
    status: 'pending',
    questionCount: 5,
    collaboratorIds: [],
    batchId: 'batch-3',
    version: 'v0.9.0',
    ownerType: 'mine',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'bank-4',
    name: 'Node.js 后端开发',
    description: 'Node.js 核心模块、Express、数据库操作',
    status: 'rejected',
    questionCount: 4,
    version: 'v0.8.0',
    ownerType: 'public',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'bank-5',
    name: 'CSS 布局与动画',
    description: 'Flexbox、Grid、CSS 动画与过渡效果',
    status: 'draft',
    questionCount: 3,
    batchId: 'batch-5',
    version: 'v0.1.0',
    ownerType: 'mine',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
]

// 模拟题目数据
export const mockQuestions: Question[] = [
  // JavaScript 基础知识题库
  {
    id: 'q-1-1',
    bankId: 'bank-1',
    type: 'single',
    content: 'JavaScript 中，typeof null 的返回值是什么？',
    options: ['null', 'undefined', 'object', 'number'],
    answer: 'object',
    analysis: '这是 JavaScript 的一个历史遗留 bug，typeof null 返回 "object"',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-1'],
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 'q-1-2',
    bankId: 'bank-1',
    type: 'multiple',
    content: '以下哪些是 JavaScript 的原始数据类型？',
    options: ['String', 'Number', 'Object', 'Boolean', 'Symbol', 'Array'],
    answer: ['String', 'Number', 'Boolean', 'Symbol'],
    analysis: 'JavaScript 原始类型包括：String、Number、Boolean、Symbol、BigInt、undefined、null',
    score: 10,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-1'],
    createdAt: new Date('2024-01-17'),
  },
  {
    id: 'q-1-3',
    bankId: 'bank-1',
    type: 'judge',
    content: 'let 和 const 声明的变量不存在变量提升。',
    answer: 'false',
    analysis: 'let 和 const 存在变量提升，但存在暂时性死区（TDZ），在声明前访问会报错',
    score: 5,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-2'],
    createdAt: new Date('2024-01-18'),
  },
  {
    id: 'q-1-4',
    bankId: 'bank-1',
    type: 'fill',
    content: 'Promise 的三种状态分别是 pending、______ 和 ______。',
    answer: ['fulfilled', 'rejected'],
    analysis: 'Promise 有三种状态：pending（等待）、fulfilled（已完成）、rejected（已拒绝）',
    score: 10,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-3'],
    createdAt: new Date('2024-01-19'),
  },
  {
    id: 'q-1-5',
    bankId: 'bank-1',
    type: 'essay',
    content: '请简述 JavaScript 事件循环（Event Loop）的工作原理。',
    answer: '参考答案：JavaScript 事件循环是处理异步操作的机制...',
    analysis: '应包含：调用栈、任务队列、微任务、宏任务等概念',
    score: 20,
    difficulty: 'hard' as Difficulty,
    knowledgePoints: ['kp-3'],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'q-1-6',
    bankId: 'bank-1',
    type: 'single',
    content: '以下代码的输出结果是什么？\nconsole.log(1 + "2" + 3)',
    options: ['6', '123', '"123"', 'NaN'],
    answer: '"123"',
    analysis: '数字与字符串相加会进行字符串拼接，1+"2"="12"，"12"+3="123"',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-1'],
    createdAt: new Date('2024-01-21'),
  },
  {
    id: 'q-1-7',
    bankId: 'bank-1',
    type: 'single',
    content: 'JavaScript 中 == 和 === 的主要区别是什么？',
    options: ['没有区别', '=== 比较类型，== 不比较', '=== 会进行类型转换', '== 会进行类型转换，=== 不会'],
    answer: '== 会进行类型转换，=== 不会',
    analysis: '== 是宽松相等，会进行类型转换；=== 是严格相等，不会进行类型转换',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-1'],
    createdAt: new Date('2024-01-22'),
  },
  {
    id: 'q-1-8',
    bankId: 'bank-1',
    type: 'multiple',
    content: '以下哪些方法可以创建数组的浅拷贝？',
    options: ['Array.from()', 'slice()', 'spread operator (...)', 'concat()', 'JSON.parse(JSON.stringify())'],
    answer: ['Array.from()', 'slice()', 'spread operator (...)', 'concat()'],
    analysis: 'JSON.parse(JSON.stringify()) 是深拷贝方法，其他都是浅拷贝',
    score: 10,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-4'],
    createdAt: new Date('2024-01-23'),
  },
  // React 框架进阶题库
  {
    id: 'q-2-1',
    bankId: 'bank-2',
    type: 'single',
    content: 'React 中，useEffect 的第二个参数是空数组时，效果等同于？',
    options: ['componentDidUpdate', 'componentDidMount', 'componentWillUnmount', 'shouldComponentUpdate'],
    answer: 'componentDidMount',
    analysis: '空依赖数组意味着 effect 只在组件挂载时执行一次',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-6'],
    createdAt: new Date('2024-02-11'),
  },
  {
    id: 'q-2-2',
    bankId: 'bank-2',
    type: 'multiple',
    content: '以下哪些 Hooks 是 React 内置的？',
    options: ['useState', 'useEffect', 'useRouter', 'useMemo', 'useCallback', 'useQuery'],
    answer: ['useState', 'useEffect', 'useMemo', 'useCallback'],
    analysis: 'useRouter 是 Next.js 的 Hook，useQuery 是 React Query 的 Hook',
    score: 10,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-6'],
    createdAt: new Date('2024-02-12'),
  },
  {
    id: 'q-2-3',
    bankId: 'bank-2',
    type: 'judge',
    content: 'React 的 useState 可以在条件语句中调用。',
    answer: 'false',
    analysis: 'Hooks 必须在函数组件的顶层调用，不能在条件语句、循环或嵌套函数中调用',
    score: 5,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-6'],
    createdAt: new Date('2024-02-13'),
  },
  {
    id: 'q-2-4',
    bankId: 'bank-2',
    type: 'fill',
    content: 'React.memo 是一个____组件，用于对函数组件进行______优化。',
    answer: ['高阶', '性能'],
    analysis: 'React.memo 是一个高阶组件，通过浅比较 props 来避免不必要的重渲染',
    score: 10,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-8'],
    createdAt: new Date('2024-02-14'),
  },
  {
    id: 'q-2-5',
    bankId: 'bank-2',
    type: 'essay',
    content: '请解释 React 中的虚拟 DOM 及其工作原理。',
    answer: '参考答案：虚拟 DOM 是真实 DOM 的 JavaScript 对象表示...',
    analysis: '应包含：虚拟 DOM 概念、diff 算法、reconciliation 过程',
    score: 20,
    difficulty: 'hard' as Difficulty,
    knowledgePoints: ['kp-8'],
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'q-2-6',
    bankId: 'bank-2',
    type: 'single',
    content: 'useCallback 主要用于什么场景？',
    options: ['缓存计算结果', '缓存函数引用', '管理副作用', '管理状态'],
    answer: '缓存函数引用',
    analysis: 'useCallback 用于缓存函数引用，避免函数在每次渲染时重新创建',
    score: 5,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-6', 'kp-8'],
    createdAt: new Date('2024-02-16'),
  },
  // TypeScript 类型系统题库
  {
    id: 'q-3-1',
    bankId: 'bank-3',
    type: 'single',
    content: 'TypeScript 中 interface 和 type 的主要区别之一是？',
    options: ['type 不能扩展', 'interface 不能描述联合类型', 'interface 可以合并声明，type 不可以', '没有区别'],
    answer: 'interface 可以合并声明，type 不可以',
    analysis: '同名 interface 会自动合并，而 type 不允许重复声明',
    score: 5,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-9'],
    createdAt: new Date('2024-03-02'),
  },
  {
    id: 'q-3-2',
    bankId: 'bank-3',
    type: 'multiple',
    content: '以下哪些是 TypeScript 的内置工具类型？',
    options: ['Partial', 'Required', 'Readonly', 'Optional', 'Pick', 'Nullable'],
    answer: ['Partial', 'Required', 'Readonly', 'Pick'],
    analysis: 'Optional 和 Nullable 不是 TypeScript 内置的工具类型',
    score: 10,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-9', 'kp-10'],
    createdAt: new Date('2024-03-03'),
  },
  {
    id: 'q-3-3',
    bankId: 'bank-3',
    type: 'fill',
    content: 'TypeScript 中使用 ______ 关键字可以定义泛型类型参数。',
    answer: ['<T>', 'T'],
    analysis: '泛型使用尖括号语法定义，如 function identity<T>(arg: T): T',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-10'],
    createdAt: new Date('2024-03-04'),
  },
  {
    id: 'q-3-4',
    bankId: 'bank-3',
    type: 'judge',
    content: 'TypeScript 中的 any 类型和 unknown 类型完全等价。',
    answer: 'false',
    analysis: 'unknown 是类型安全的 any，使用 unknown 类型的值之前必须进行类型检查',
    score: 5,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-9'],
    createdAt: new Date('2024-03-05'),
  },
  {
    id: 'q-3-5',
    bankId: 'bank-3',
    type: 'essay',
    content: '请解释 TypeScript 中的条件类型（Conditional Types）及其使用场景。',
    answer: '参考答案：条件类型使用 T extends U ? X : Y 语法...',
    analysis: '应包含：条件类型语法、infer 关键字、分布式条件类型',
    score: 20,
    difficulty: 'hard' as Difficulty,
    knowledgePoints: ['kp-9', 'kp-10'],
    createdAt: new Date('2024-03-06'),
  },
  // Node.js 后端开发题库
  {
    id: 'q-4-1',
    bankId: 'bank-4',
    type: 'single',
    content: 'Node.js 中哪个模块用于处理文件系统操作？',
    options: ['http', 'path', 'fs', 'os'],
    answer: 'fs',
    analysis: 'fs 模块提供了文件读写、目录操作等文件系统 API',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-13'],
    createdAt: new Date('2024-03-11'),
  },
  {
    id: 'q-4-2',
    bankId: 'bank-4',
    type: 'multiple',
    content: '以下哪些是 Express 中间件的正确使用方式？',
    options: ['app.use(middleware)', 'router.use(middleware)', 'app.get("/", middleware, handler)', '以上都是'],
    answer: ['app.use(middleware)', 'router.use(middleware)', 'app.get("/", middleware, handler)'],
    analysis: 'Express 中间件可以在应用级、路由级或路由处理器级别使用',
    score: 10,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-14'],
    createdAt: new Date('2024-03-12'),
  },
  {
    id: 'q-4-3',
    bankId: 'bank-4',
    type: 'judge',
    content: 'Node.js 是单线程的，因此不能处理并发请求。',
    answer: 'false',
    analysis: 'Node.js 虽然是单线程的，但通过事件循环和异步 I/O 可以高效处理并发请求',
    score: 5,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-13'],
    createdAt: new Date('2024-03-13'),
  },
  {
    id: 'q-4-4',
    bankId: 'bank-4',
    type: 'essay',
    content: '请说明 Node.js 中 require 和 import 的区别。',
    answer: '参考答案：require 是 CommonJS 模块系统的导入方式...',
    analysis: '应包含：CommonJS vs ES Modules、同步 vs 异步、静态分析等',
    score: 15,
    difficulty: 'hard' as Difficulty,
    knowledgePoints: ['kp-13'],
    createdAt: new Date('2024-03-14'),
  },
  // CSS 布局与动画题库
  {
    id: 'q-5-1',
    bankId: 'bank-5',
    type: 'single',
    content: 'Flexbox 中，justify-content 属性控制的是哪个方向的对齐？',
    options: ['交叉轴', '主轴', '垂直方向', '水平方向'],
    answer: '主轴',
    analysis: 'justify-content 控制主轴方向的对齐，align-items 控制交叉轴方向',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-11'],
    createdAt: new Date('2024-03-21'),
  },
  {
    id: 'q-5-2',
    bankId: 'bank-5',
    type: 'multiple',
    content: '以下哪些是 CSS Grid 的有效属性？',
    options: ['grid-template-columns', 'grid-gap', 'grid-flow', 'grid-auto-rows', 'grid-justify'],
    answer: ['grid-template-columns', 'grid-gap', 'grid-auto-rows'],
    analysis: 'grid-flow 不存在，应该是 grid-auto-flow；grid-justify 不存在',
    score: 10,
    difficulty: 'medium' as Difficulty,
    knowledgePoints: ['kp-11'],
    createdAt: new Date('2024-03-22'),
  },
  {
    id: 'q-5-3',
    bankId: 'bank-5',
    type: 'fill',
    content: 'CSS 动画需要使用 @______ 规则来定义关键帧。',
    answer: ['keyframes'],
    analysis: '@keyframes 用于定义动画的关键帧序列',
    score: 5,
    difficulty: 'easy' as Difficulty,
    knowledgePoints: ['kp-12'],
    createdAt: new Date('2024-03-23'),
  },
]

// 模拟试卷数据
export const mockExams: Exam[] = [
  {
    id: 'exam-1',
    name: '前端基础测试',
    description: '考察 JavaScript、React 基础知识',
    status: 'published',
    totalScore: 100,
    duration: 60,
    collaboratorIds: ['user-2'],
    collaboratorDeptIds: ['dept-1'],
    batchId: 'batch-1',
    version: 'v1.0.0',
    ownerType: 'mine',
    questions: [
      {
        id: 'eq-1',
        questionId: 'q-1-1',
        type: 'single',
        content: 'JavaScript 中，typeof null 的返回值是什么？',
        options: ['null', 'undefined', 'object', 'number'],
        answer: 'object',
        analysis: '这是 JavaScript 的一个历史遗留 bug，typeof null 返回 "object"',
        score: 10,
        order: 1,
      },
      {
        id: 'eq-2',
        questionId: 'q-1-2',
        type: 'multiple',
        content: '以下哪些是 JavaScript 的原始数据类型？',
        options: ['String', 'Number', 'Object', 'Boolean', 'Symbol', 'Array'],
        answer: ['String', 'Number', 'Boolean', 'Symbol'],
        analysis: 'JavaScript 原始类型包括：String、Number、Boolean、Symbol、BigInt、undefined、null',
        score: 15,
        order: 2,
      },
      {
        id: 'eq-3',
        questionId: 'q-2-1',
        type: 'single',
        content: 'React 中，useEffect 的第二个参数是空数组时，效果等同于？',
        options: ['componentDidUpdate', 'componentDidMount', 'componentWillUnmount', 'shouldComponentUpdate'],
        answer: 'componentDidMount',
        analysis: '空依赖数组意味着 effect 只在组件挂载时执行一次',
        score: 10,
        order: 3,
      },
      {
        id: 'eq-4',
        questionId: 'q-1-5',
        type: 'essay',
        content: '请简述 JavaScript 事件循环（Event Loop）的工作原理。',
        answer: '参考答案：JavaScript 事件循环是处理异步操作的机制...',
        analysis: '应包含：调用栈、任务队列、微任务、宏任务等概念',
        score: 25,
        order: 4,
      },
      {
        id: 'eq-5',
        questionId: 'q-2-5',
        type: 'essay',
        content: '请解释 React 中的虚拟 DOM 及其工作原理。',
        answer: '参考答案：虚拟 DOM 是真实 DOM 的 JavaScript 对象表示...',
        analysis: '应包含：虚拟 DOM 概念、diff 算法、reconciliation 过程',
        score: 25,
        order: 5,
      },
      {
        id: 'eq-6',
        questionId: 'q-1-3',
        type: 'judge',
        content: 'let 和 const 声明的变量不存在变量提升。',
        answer: 'false',
        analysis: 'let 和 const 存在变量提升，但存在暂时性死区（TDZ），在声明前访问会报错',
        score: 5,
        order: 6,
      },
      {
        id: 'eq-7',
        questionId: 'q-1-4',
        type: 'fill',
        content: 'Promise 的三种状态分别是 pending、______ 和 ______。',
        answer: ['fulfilled', 'rejected'],
        analysis: 'Promise 有三种状态：pending（等待）、fulfilled（已完成）、rejected（已拒绝）',
        score: 10,
        order: 7,
      },
    ],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'exam-2',
    name: 'TypeScript 能力测试',
    description: '考察 TypeScript 类型系统掌握程度',
    status: 'pending',
    totalScore: 50,
    duration: 30,
    collaboratorIds: ['user-1', 'user-3'],
    batchId: 'batch-2',
    version: 'v0.9.0',
    ownerType: 'collaborate',
    questions: [
      {
        id: 'eq-2-1',
        questionId: 'q-3-1',
        type: 'single',
        content: 'TypeScript 中 interface 和 type 的主要区别之一是？',
        options: ['type 不能扩展', 'interface 不能描述联合类型', 'interface 可以合并声明，type 不可以', '没有区别'],
        answer: 'interface 可以合并声明，type 不可以',
        analysis: '同名 interface 会自动合并，而 type 不允许重复声明',
        score: 10,
        order: 1,
      },
      {
        id: 'eq-2-2',
        questionId: 'q-3-2',
        type: 'multiple',
        content: '以下哪些是 TypeScript 的内置工具类型？',
        options: ['Partial', 'Required', 'Readonly', 'Optional', 'Pick', 'Nullable'],
        answer: ['Partial', 'Required', 'Readonly', 'Pick'],
        analysis: 'Optional �� Nullable 不是 TypeScript 内置的工具类型',
        score: 15,
        order: 2,
      },
      {
        id: 'eq-2-3',
        questionId: 'q-3-5',
        type: 'essay',
        content: '请解释 TypeScript 中的条件类型（Conditional Types）及其使用场景。',
        answer: '参考答案：条件类型使用 T extends U ? X : Y 语法...',
        analysis: '应包含：条件类型语法、infer 关键字、分布式条件类型',
        score: 25,
        order: 3,
      },
    ],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'exam-3',
    name: '全栈开发综合测试',
    description: '综合考察前后端开发能力',
    status: 'draft',
    totalScore: 0,
    duration: 90,
    version: 'v0.1.0',
    ownerType: 'public',
    questions: [],
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-25'),
  },
]
